version: '3.8'
services:
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    ports:
      - "6379:6379"  # Expose for debugging (optional)

  app:
    depends_on:
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # FastAPI port
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL}
      - REDIS_HOST=redis
    volumes:
      - ./data:/app/data 
    command: ["uvicorn", "mcp.main:app", "--host", "0.0.0.0", "--port", "8000"]